import { describe, it, expect } from 'vitest';
import { encodeState, decodeState } from './url';
import {
  ASSUMPTION_COUNT_MAX,
  ASSUMPTION_MAX,
  PAYLOAD_BUDGET,
  SCHEMA_VERSION,
  SENTENCE_MAX,
  type ModelState,
} from './schema';
import { PARAM_KEYS, type Params } from './engine';

/**
 * The v1 wire contract. Read docs/URL-CONTRACT.md before changing anything in this file:
 * a failure here means links already shared have stopped working, and there is no database
 * to migrate them with.
 */

const PARAMS: Params = {
  startingCash: 18000,
  monthlyBurn: 9500,
  customers: 12,
  price: 400,
  churn: 0.08,
  newPerMonth: 2,
};

/**
 * Frozen. Generated once from a fully-populated v1 state and pasted here as a literal, so it
 * is not regenerated by the code it is meant to police. If this stops decoding, a change has
 * broken every link in the wild.
 */
const GOLDEN_V1 =
  'eyJ2IjoxLCJzIjoiMThrIGluIHRoZSBiYW5rLCA5LjVrIGEgbW9udGggYnVybiwgMTIgY3VzdG9tZXJzIHBheWluZyA0MDAsIGFib3V0IDglIGNodXJuLCAyIG5ldyBjdXN0b21lcnMgYSBtb250aCIsInAiOnsic3RhcnRpbmdDYXNoIjoxODAwMCwibW9udGhseUJ1cm4iOjk1MDAsImN1c3RvbWVycyI6MTIsInByaWNlIjo0MDAsImNodXJuIjowLjA4LCJuZXdQZXJNb250aCI6Mn0sImEiOlsiQ2h1cm4gaXMgYSBmbGF0IDglIGVhY2ggbW9udGgsIGFwcGxpZWQgYmVmb3JlIG5ldyBzaWdudXBzIGxhbmQuIiwiQnVybiBzdGF5cyBhdCAkOSw1MDAgYW5kIGRvZXMgbm90IHJpc2UgYXMgdGhlIGN1c3RvbWVyIGNvdW50IGdyb3dzLiJdLCJpIjpbImNodXJuIl0sIm8iOnsic3RhcnRpbmdDYXNoIjoxODAwMCwibW9udGhseUJ1cm4iOjk1MDAsImN1c3RvbWVycyI6MTIsInByaWNlIjo0MDAsImNodXJuIjowLjA1LCJuZXdQZXJNb250aCI6Mn0sImYiOiJrM24ycDFxIn0';

describe('v1 links must keep working forever', () => {
  it('decodes the frozen golden payload', () => {
    const state = decodeState(GOLDEN_V1);
    expect(state).not.toBeNull();
    expect(state!.v).toBe(SCHEMA_VERSION);
    expect(state!.p).toEqual(PARAMS);
    expect(state!.i).toEqual(['churn']);
    expect(state!.o?.churn).toBe(0.05);
    expect(state!.f).toBe('k3n2p1q');
    expect(state!.a).toHaveLength(2);
    expect(state!.s).toContain('18k in the bank');
  });

  it('re-encodes the golden payload to exactly itself', () => {
    // Canonical serialisation means a decode/encode cycle is the identity function.
    expect(encodeState(decodeState(GOLDEN_V1)!)).toBe(GOLDEN_V1);
  });

  it('ignores fields a future version adds, rather than refusing the link', () => {
    // Forward compatibility: an older client must not choke on a newer client's payload.
    const withExtra = { ...JSON.parse(atob(GOLDEN_V1.replace(/-/g, '+').replace(/_/g, '/'))), zz: 'future' };
    const encoded = btoa(JSON.stringify(withExtra)).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
    const state = decodeState(encoded);
    expect(state).not.toBeNull();
    expect(state).not.toHaveProperty('zz');
  });

  it('refuses a version it cannot decode instead of guessing', () => {
    const v2 = { ...JSON.parse(atob(GOLDEN_V1.replace(/-/g, '+').replace(/_/g, '/'))), v: 2 };
    const encoded = btoa(JSON.stringify(v2)).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
    expect(decodeState(encoded)).toBeNull();
  });
});

describe('canonical serialisation', () => {
  const base: ModelState = { v: 1, s: 'x', p: PARAMS, a: [] };

  it('gives one model exactly one URL, whatever order it was built in', () => {
    const scrambled: Params = {
      newPerMonth: 2,
      churn: 0.08,
      price: 400,
      customers: 12,
      monthlyBurn: 9500,
      startingCash: 18000,
    };
    expect(encodeState({ ...base, p: scrambled })).toBe(encodeState(base));
  });

  it('orders the guessed-field list, since it is a set and not a sequence', () => {
    const a = encodeState({ ...base, i: ['churn', 'customers'] });
    const b = encodeState({ ...base, i: ['customers', 'churn'] });
    expect(a).toBe(b);
  });

  it('is stable across a round trip', () => {
    const once = encodeState(base);
    expect(encodeState(decodeState(once)!)).toBe(once);
  });
});

describe('payload budget', () => {
  /** Every optional field present, every cap maxed, twelve digits in all six slots. */
  const worstCase: ModelState = {
    v: 1,
    s: 'x'.repeat(SENTENCE_MAX),
    p: {
      startingCash: 999999999999,
      monthlyBurn: 999999999999,
      customers: 999999999,
      price: 999999999,
      churn: 0.123456,
      newPerMonth: 999999999,
    },
    a: Array(ASSUMPTION_COUNT_MAX).fill('x'.repeat(ASSUMPTION_MAX)),
    i: [...PARAM_KEYS],
    o: {
      startingCash: 999999999999,
      monthlyBurn: 999999999999,
      customers: 999999999,
      price: 999999999,
      churn: 0.123456,
      newPerMonth: 999999999,
    },
    f: 'abcdefghijklmnop',
  };

  it('cannot exceed the budget, even at every cap simultaneously', () => {
    const size = encodeState(worstCase).length;
    expect(size).toBeLessThanOrEqual(PAYLOAD_BUDGET);
  });

  it('stays under the universally safe 2000-character URL line, og prefix included', () => {
    expect(`/api/og?d=${encodeState(worstCase)}`.length).toBeLessThan(2000);
  });

  it('refuses an over-budget payload at the boundary, before parsing it', () => {
    expect(decodeState('e'.repeat(PAYLOAD_BUDGET + 1))).toBeNull();
  });

  it('keeps a typical model far below the cap', () => {
    expect(encodeState({ v: 1, s: 'x'.repeat(100), p: PARAMS, a: [] }).length).toBeLessThan(400);
  });
});
